export const grayscaleInput = document.getElementById('grayscaleInput')
export const sepiaInput = document.getElementById('sepiaInput')
export const blurInput = document.getElementById('blurInput')
export const brightnessInput = document.getElementById('brightnessInput')
export const hueRotateInput = document.getElementById('hueRotateInput')
export const saturateInput = document.getElementById('saturateInput')
export const contrastInput = document.getElementById('contrastInput')
export const opacityInput = document.getElementById('opacityInput')
export const invertInput = document.getElementById('invertInput')

export const resetButton = document.getElementById('resetButton')
export const codeTextarea = document.getElementById('textarea')
